#!/bin/sh
#
prog="fetchplacardinfo"
usage="$prog [ergdb]"
#
#	Fetch the placard list for each entry in ergdb, and write a line
#	per un number to stdout:
#	un <tab> plac1.gif plac2.gif ...

case $# in
0|1)	;;
*)	echo "$usage" 1>&2
	exit 1
esac

ERGURL="https://cameochemicals.noaa.gov/report?key=UN${UN}"

awk '{print $1}' $* |
while read un
do
	echo -n "$un " 1>&2

	curl -s -S "$ERGURL"	|
	grep /images/placards/	|
	sed 's/^.*\/images\/placards\///'	|
	sed 's/".*$//'	|
	sort -u		|
	tr '\n' ' '	|
	sed "s/^/$UN	/"
	echo		# add newline
done |
grep '^[0-9][0-9][0-9][0-9]'	|
awk -v FS="	" 'NF > 1 { print }'

