#!/bin/sh
#
prog="processplacards"
usage="$prog [ergdb]"
#
#	Fetch placard images for each chemical, an populate the placard
#	database from ERG.
#
#	Stdin has the ergdb, and we use the first field, the UN number.
#
#	The database is written to stdout, the placards put in the placard
#	subdirectory


case $# in
0|1)	;;
*)	echo "$usage" 1>&2
	exit 1
esac

WRKDIR=${WRKDIR:-${TMPDIR}/${prog}}
mkdir -p $WRKDIR

imagelist=$WRKDIR/imagelist
>$imagelist

awk '{print $1}' $* |
while read un
do
	echo -n "$un " 1>&2
	getergplacards $un $imagelist
done | tee $WRKDIR/placardraw | 
grep '^[0-9][0-9][0-9][0-9]'	|
awk -v FS="	" 'NF > 1 { print }'
